(custom-set-variables
 '(abbrev-mode t t)
 '(bell-volume 0)
 '(c-electric-pound-behavior (quote (alignleft)))
 '(c-set-offset (quote substatement-open) t)
 '(column-number-mode t)
 '(fill-column 78)
 '(font-lock-auto-fontify t)
 '(font-lock-maximum-decoration t)
 '(font-lock-maximum-size nil)
 '(font-lock-mode t nil (font-lock))
 '(font-lock-use-colors nil)
 '(font-lock-use-fonts t)
 '(font-lock-verbose nil)
 '(font-menu-ignore-scaled-fonts t t)
 '(font-menu-this-frame-only-p t t)
 '(global-font-lock-mode t nil (font-lock))
 '(gutter-buffers-tab-visible-p nil)
 '(indent-tabs-mode t)
 '(ispell-program-name "aspell" t)
 '(kde-emacs-after-parent-string " ")
 '(kde-emacs-delete-trailing-whitespace t)
 '(kde-emacs-make "bjam")
 '(kde-email "ulrich.kuettler@theppro.com")
 '(kde-full-name "Ulrich Küttler")
 '(kde-header-protection-parts-to-show 3)
 '(line-number-mode t)
 '(magic-keys-mode nil)
 '(magic-parens-mode nil)
 '(make-backup-files nil)
 '(mode-compile-make-options "" t)
 '(modeline-scrolling-method t)
 '(paren-mode (quote paren) nil (paren))
 '(query-user-mail-address nil)
 '(require-final-newline t)
 '(scroll-step 1)
 '(tab-width 4)
 '(toolbar-visible-p nil)
 '(track-eol t)
 '(transient-mark-mode t)
 '(truncate-lines t)
 '(user-mail-address "uli@localhost.localdomain"))
(custom-set-faces
 '(default ((t (:size "12pt" :family "Fixed"))) t)
 '(bold ((t (:size "12pt" :family "Fixed"))) t)
 '(bold-italic ((t (:size "12pt" :family "Fixed"))) t)
 '(italic ((t (:size "12pt" :family "Fixed"))) t)
 '(shell-output-face ((t (:size "12pt" :family "Fixed"))) t))
